apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s-example
  template:
    metadata:
      labels:
        app: springboot-k8s-example
    spec:
      containers:
        - name: springboot-k8s-example
          image: springboot-k8s-example:1.0
          ports:
            - containerPort: 8080