apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-example
spec:
  selector:
    app: springboot-k8s-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: grpc
  type: NodePort
